// <auto-generated />
using System;
using Microservice.Whatevers.Repositories.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Microservice.Whatevers.Repositories.Migrations
{
    [DbContext(typeof(WhateverContext))]
    [Migration("20200430014616_First migration")]
    partial class Firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Microservice.Whatevers.Domain.Entities.Things.Thing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("WhateverId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WhateverId");

                    b.ToTable("Thing");
                });

            modelBuilder.Entity("Microservice.Whatevers.Domain.Entities.Whatevers.Whatever", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Whatever");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ade861ad-896a-4597-a5fa-9ab8701b95f8"),
                            Name = "Whatever",
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = "Some type"
                        },
                        new
                        {
                            Id = new Guid("cb147508-a894-465f-8040-bb1076e353f9"),
                            Name = "Whatever",
                            Time = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            Type = "Another type"
                        },
                        new
                        {
                            Id = new Guid("88013e84-3f5e-4c47-8d76-5add972d6735"),
                            Name = "Whatever",
                            Time = new DateTime(2020, 4, 29, 22, 46, 15, 583, DateTimeKind.Local).AddTicks(5552),
                            Type = "More another type"
                        },
                        new
                        {
                            Id = new Guid("ef2a6fad-5bcd-4a11-a3ae-be8555fc2791"),
                            Name = "Whatever",
                            Time = new DateTime(2020, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            Type = "Once more another type"
                        });
                });

            modelBuilder.Entity("Microservice.Whatevers.Domain.Entities.Things.Thing", b =>
                {
                    b.HasOne("Microservice.Whatevers.Domain.Entities.Whatevers.Whatever", null)
                        .WithMany("Things")
                        .HasForeignKey("WhateverId");
                });
#pragma warning restore 612, 618
        }
    }
}
